---
title: "Diagnostic Plots"
subtitle: "A Comparison of Post-Exercise Recovery Modalities: A Systematic Review and Meta-Analysis"
date: last-modified
date-format: long
format: html
toc: true
number-sections: true
author:
  - name: Bailey Cameron
    affil-id: 1
    orcid: 0009-0005-8964-9811
    corresponding: true
    email: 5cameb31@solent.ac.uk
    affiliations:
        - id: 1
          name: Solent University, Southampton, Hampshire, UK
  - name: Lee Bridgeman
    affil-id: 1
    orcid: 0000-0002-7605-4289
    email: lee.bridgeman@solent.ac.uk
    affiliations:
        - id: 1
          name: Solent University, Southampton, Hampshire, UK
  - name: Vickie Wong
    affil-id: 1
    orcid: 0000-0001-5002-7584
    email: vickie.wong@solent.ac.uk
    affiliations:
        - id: 1
          name: Solent University, Southampton, Hampshire, UK
  - name: Scott Burnet
    affil-id: 1
    # orcid: 0000-0002-8003-0757
    corresponding: true
    email: scott.burnet@solent.ac.uk
    affiliations:
        - id: 1
          name: Solent University, Southampton, Hampshire, UK
  - name: James Steele
    affil-id: 2,3,4
    orcid: 0000-0002-8003-0757
    corresponding: true
    email: james@steele-research.com
    affiliations:
        - id: 2
          name: Steele Research Limited, Eastleigh, Hampshire, UK
        - id: 2
          name: MacroFactor, Raleigh, North Carolina, USA
        - id: 4
          name: School of Health and Biomedical Sciences, Royal Melbourne Institute of Technology, Melbourne, VIC, Australia
execute: 
  message: false
  warning: false
  echo: false
---
```{r}
targets::tar_config_set(store = here::here('_targets'))

```


# Performance Model

## $\hat{R}$

```{r}

targets::tar_load(rhat_performance_model)

rhat_performance_model 


```

## Trace plots

```{r}

targets::tar_load(trace_plot_performance_model)

trace_plot_performance_model

```

## Posterior predictive check

```{r}

targets::tar_load(pp_check_performance_model)

pp_check_performance_model

```

# Biochemical Model

## $\hat{R}$

```{r}

targets::tar_load(rhat_biochemical_model)

rhat_biochemical_model 


```

## Trace plots

```{r}

targets::tar_load(trace_plot_biochemical_model)

trace_plot_biochemical_model

```

## Posterior predictive check

```{r}

targets::tar_load(pp_check_biochemical_model)

pp_check_biochemical_model

```

# Perceptual Model

## $\hat{R}$

```{r}

targets::tar_load(rhat_perceptual_model)

rhat_perceptual_model 


```

## Trace plots

```{r}

targets::tar_load(trace_plot_perceptual_model)

trace_plot_perceptual_model

```

## Posterior predictive check

```{r}

targets::tar_load(pp_check_perceptual_model)

pp_check_perceptual_model

```
